"""Graph state definitions and Pydantic schemas for Deep Agentic Market Intelligence."""

import operator
from typing import Annotated, Dict, List, Literal, Optional

from pydantic import BaseModel, Field
from typing_extensions import TypedDict

TaskStatus = Literal["pending", "active", "done"]


# --------------------------------------------------------------------------- #
# Planning
# --------------------------------------------------------------------------- #
class SubQuestion(BaseModel):
    """A decomposed research sub-question (a research branch)."""

    question: str = Field(description="The research sub-question to investigate")
    category: str = Field(
        description="Market category this sub-question targets, e.g. oral care"
    )
    rationale: str = Field(
        description="Why this sub-question matters for market intelligence"
    )
    language: str = Field(
        default="English",
        description="Language/region lens for this branch, e.g. English, Spanish",
    )


class SubQuestionList(BaseModel):
    """List of sub-questions generated by the planner."""

    sub_questions: List[SubQuestion] = Field(
        description="List of focused, branch-aware research sub-questions"
    )


# --------------------------------------------------------------------------- #
# Signal vs. noise
# --------------------------------------------------------------------------- #
class Signal(BaseModel):
    """A scored market signal extracted from evidence."""

    statement: str = Field(description="A concrete market signal or claim")
    score: float = Field(
        description="Signal strength 0.0 (noise) to 1.0 (strong signal)"
    )
    is_signal: bool = Field(
        description="True if this is a meaningful market signal vs temporary noise"
    )
    reasoning: str = Field(description="Why this is a signal or noise")
    category: str = Field(default="", description="Category this signal belongs to")

    # Statistical signal-detection fields (populated post-hoc, not by the LLM)
    statistical_score: float = Field(
        default=0.0, description="Evidence-derived statistical support score (0-1)"
    )
    source_count: int = Field(
        default=0, description="Number of corroborating evidence items"
    )
    source_types: List[str] = Field(
        default_factory=list, description="Distinct source types corroborating it"
    )
    combined_score: float = Field(
        default=0.0, description="Blended reasoning + statistical score (0-1)"
    )


class SignalTrend(BaseModel):
    """How a signal's strength has evolved across runs (perception over time)."""

    subject: str = Field(description="The signal subject/statement tracked over time")
    category: str = Field(default="")
    current_score: float = Field(description="Combined score in the current run")
    previous_score: Optional[float] = Field(
        default=None, description="Combined score in the prior run, if any"
    )
    delta: float = Field(default=0.0, description="current - previous")
    direction: str = Field(
        default="new", description="new | rising | falling | stable"
    )
    observations: int = Field(
        default=1, description="How many runs this subject has appeared in"
    )


class SignalList(BaseModel):
    signals: List[Signal] = Field(description="Scored signals from the evidence")


# --------------------------------------------------------------------------- #
# Knowledge graph
# --------------------------------------------------------------------------- #
class Entity(BaseModel):
    """An entity in the market knowledge graph."""

    name: str = Field(description="Entity name")
    type: str = Field(
        description="One of: brand, product, company, community, trend, attribute, region"
    )


class Relationship(BaseModel):
    """A directed relationship between two entities."""

    source: str = Field(description="Source entity name")
    target: str = Field(description="Target entity name")
    relation: str = Field(
        description="Relationship label, e.g. competes_with, driven_by, popular_in"
    )


class KnowledgeGraph(BaseModel):
    """A dynamic market knowledge graph."""

    entities: List[Entity] = Field(default_factory=list)
    relationships: List[Relationship] = Field(default_factory=list)

    def merge(self, other: "KnowledgeGraph") -> "KnowledgeGraph":
        """Merge another graph into this one, de-duplicating by name/relation."""
        seen_entities = {(e.name.lower(), e.type.lower()) for e in self.entities}
        for e in other.entities:
            key = (e.name.lower(), e.type.lower())
            if key not in seen_entities:
                self.entities.append(e)
                seen_entities.add(key)

        seen_rels = {
            (r.source.lower(), r.target.lower(), r.relation.lower())
            for r in self.relationships
        }
        for r in other.relationships:
            key = (r.source.lower(), r.target.lower(), r.relation.lower())
            if key not in seen_rels:
                self.relationships.append(r)
                seen_rels.add(key)
        return self


# --------------------------------------------------------------------------- #
# Synthesis
# --------------------------------------------------------------------------- #
class BrandInsight(BaseModel):
    """Structured insight about an emerging competitor brand."""

    brand_name: str = Field(description="Name of the emerging competitor brand")
    category: str = Field(description="Category where this brand competes")
    pg_products_competed: List[str] = Field(
        description="Specific incumbent brands/products this competitor challenges"
    )
    why_popular: List[str] = Field(
        description="Key reasons consumers are choosing this brand"
    )
    theme_tags: List[str] = Field(
        description="Consumer preference themes, e.g. sustainability, DTC"
    )
    evidence_summary: str = Field(
        description="Brief summary of supporting evidence from research"
    )


class ThemeCluster(BaseModel):
    """A cluster of consumer preference themes across brands."""

    theme: str = Field(description="The consumer preference theme")
    description: str = Field(
        description="How this theme drives consumer choice across emerging brands"
    )
    example_brands: List[str] = Field(description="Brands exemplifying this theme")


class SynthesisResult(BaseModel):
    """Synthesized findings across all evidence."""

    brand_insights: List[BrandInsight] = Field(
        description="Structured insights per emerging competitor brand"
    )
    theme_clusters: List[ThemeCluster] = Field(
        description="Cross-brand consumer preference themes"
    )
    key_trends: List[str] = Field(
        description="High-level market trends and business insights"
    )


# --------------------------------------------------------------------------- #
# Thinker / verifier
# --------------------------------------------------------------------------- #
class ReasoningStep(BaseModel):
    """A single step in the sequential-thinking reasoning trace."""

    step: int = Field(description="Step number in the reasoning chain")
    thought: str = Field(description="The reasoning content for this step")
    conclusion: str = Field(default="", description="Interim conclusion, if any")


class VerifierResult(BaseModel):
    """Output of the thinker/verifier agent."""

    is_sufficient: bool = Field(
        description="Whether current evidence is sufficient to write the report"
    )
    confidence: float = Field(
        description="Confidence 0.0-1.0 in the current research coverage"
    )
    gaps: List[str] = Field(description="Identified gaps in research coverage")
    reasoning_steps: List[ReasoningStep] = Field(
        default_factory=list, description="Sequential reasoning trace"
    )
    follow_up_questions: List[SubQuestion] = Field(
        default_factory=list, description="Follow-up sub-questions to address gaps"
    )


# --------------------------------------------------------------------------- #
# Evidence + research-state tracking
# --------------------------------------------------------------------------- #
class EvidenceItem(TypedDict):
    """A single piece of research evidence."""

    sub_question: str
    category: str
    language: str
    source_title: str
    source_url: str
    source_type: str  # "web" or "community"
    reliability: float
    snippet: str
    summary: str


class TaskRecord(TypedDict):
    """A tracked research task for long-horizon state."""

    id: str
    question: str
    category: str
    language: str
    status: TaskStatus
    loop: int


# --------------------------------------------------------------------------- #
# Graph state
# --------------------------------------------------------------------------- #
class ResearchState(TypedDict):
    """Shared state flowing through the LangGraph research workflow."""

    research_question: str
    target: str
    sub_questions: List[SubQuestion]
    pending_sub_questions: List[SubQuestion]

    # Long-horizon research-state tracking
    task_records: Annotated[List[TaskRecord], operator.add]
    running_summary: str

    # Accumulated evidence and signals
    evidence: Annotated[List[EvidenceItem], operator.add]
    signals: Annotated[List[Signal], operator.add]

    # Statistically re-scored, ranked signals (overwritten, not accumulated)
    ranked_signals: List[Signal]
    # Perception-over-time trends vs prior runs (serialized SignalTrend dicts)
    signal_trends: List[Dict]

    # Dynamic knowledge graph (serialized dict for state portability)
    knowledge_graph: Dict

    # Verifier / synthesis outputs
    reasoning_trace: List[ReasoningStep]
    confidence: float
    gaps: List[str]
    synthesis: Optional[SynthesisResult]
    report: str

    loop_count: int
    max_loops: int
    research_sufficient: bool


class ResearchTask(TypedDict):
    """Per-task state for parallel research branches."""

    sub_question: SubQuestion
    research_question: str
    target: str
    loop: int
